# app.yaml
runtime: python310  # Using Python 3.10

entrypoint: gunicorn -b :$PORT app:server

instance_class: F2  # Standard instance size, adjust as needed

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  # Environment variables if needed
  PYTHONUNBUFFERED: "TRUE"