steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy --quiet
timeout: '900s' # Optional: sets the timeout for the build process
options:
  logging: CLOUD_LOGGING_ONLY  # Added this line to fix the service account error